### ISSUE TITLE
Need help installing app 

### ISSUE THREAD

**Issue by briandonna** [boeyum/WizWiFi#1]
HI Boeyum,

I love the fact that you have created an app that does not have the need for the cloud, I started using homey for that very reason! To get my devices and home off the cloud. I soon realized that even though I have a Homey hub many devices still depend on the cloud, and some seem to have no workaround as if they're forcing you to use the cloud. So, I'm glad to see you were able to make an app to use wiz lighting devices without being forced to use their cloud service. 

I would love to use this app right away, but I am not familiar with the developer section of homey nor how to get and install the code from GitHub to homey. 
If you wouldn't mind, would you please give me some instructions for dummies on how to install your app on the homey developer side?

Thank You very much! 
Brian Chaney

**Comment by boeyum** [comment]
Sorry for late answere, I have been on a short vacation trip. Since the app are i Beta vesion, it will not be present on the Homey Community app store (or any other). To install the app you have to do it the developer way. You have to install NoneJS on a PC/MAC and download the project from github. On this site you will find how to install Homey developent system and commands used to install the app. Note: It's still some flow issues with the app that I'm trying to fix. A new version willbe on the girthub when I'm done.

Jan-Ivar Bøyum

**Comment by boeyum** [comment]
Sorry, forgot the site link: https://tools.developer.homey.app
